UI fixes
polywrap/hub pull request #98
Opened 2021-09-09 17:11 UTC by Brioline

2021-09-16 12:15 UTC, cbrzn requested changes
The responsive view looks amazing, there are a few details to fix but looking good

2021-09-16 12:15 UTC, cbrzn commented on src/components/Navigation/NavItem.tsx
> +export default React.memo(NavItem);
Just curious: What's the reason for exporting it as a memoized component?

2021-09-16 12:15 UTC, cbrzn commented on src/components/Layout.tsx
> +        <MobileNav />
Currently, if we go to Wrapper details there's two headers, would it be possible that this line of code is causing it? Once again, this is my first thought and I can be wrong about the error is this line 
<img width="1789" alt="Screenshot 2021-09-16 at 14 04 25" src="https://user-images.githubusercontent.com/21031138/133608951-f60db8bd-1265-40a0-9369-6aa488185316.png">

2021-09-16 12:15 UTC, cbrzn commented on src/components/Spinner.tsx
> +export default React.memo(Spinner)
Same question, any reason on using memoized components?

2021-09-16 12:15 UTC, cbrzn commented on src/pages/index.tsx
> +import Header from "../components/Header";
I guess we can remove this? Unless I am missing something...
```suggestion
```

2021-09-16 12:15 UTC, cbrzn commented on src/pages/test.tsx
>  /** @jsxImportSource theme-ui **/
Feel free to remove this file whenever you feel like it :-D

2021-09-16 12:15 UTC, cbrzn commented on src/state/initialState.ts
> +type MobileType = {
Would it be possible to use the same variable to show the mobile navbar and mobile view? I feel it's kind of redundant - Unless there's a good reason for doing it this way

2021-09-16 16:19 UTC, Brioline commented on src/components/Navigation/NavItem.tsx
> +export default React.memo(NavItem);
I dont think there is a reason to rerender this component

2021-09-16 16:26 UTC, Brioline commented on src/state/initialState.ts
> +type MobileType = {
Don't understand what exactly do you mean ? Reason for "isMobileNavActive" is not to create new React Context.

2021-09-16 16:28 UTC, Brioline commented on src/components/Layout.tsx
> +      window.innerWidth <= 375 &&
intermediate responsive is the next step

2021-09-16 16:53 UTC, Brioline commented on src/pages/test.tsx
>  /** @jsxImportSource theme-ui **/
Removed

2021-09-16 16:54 UTC, Brioline commented on src/pages/index.tsx
> +import Header from "../components/Header";
All unnecessary imports removed

2021-09-16 16:54 UTC, Brioline commented on src/components/Layout.tsx
> +        <MobileNav />
Fixed

2021-09-16 16:54 UTC, Brioline commented on src/components/CreateApi/UploadBy/EnsAddress.tsx
> +  console.log(publish);
Removed

2021-09-16 16:55 UTC, Brioline commented on public/images/user.svg
> +<svg width="140" height="140" viewBox="0 0 140 140" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Fixed

2021-09-17 07:16 UTC, Brioline commented on src/components/CreateApi/Start.tsx
> +const styles: { [key: string]: ThemeUICSSObject } = {
I suggest create separate folders for every component/comnonent group and place styles in file next to component file. How do you think ?

2021-09-20 07:42 UTC, Brioline commented on src/state/initialState.ts
> +type MobileType = {
Handled with React Context and hook using this context

2021-09-20 12:41 UTC, Brioline commented on src/components/Spinner.tsx
> +export default React.memo(Spinner)
Removed memoizing

2021-09-20 14:40 UTC, Brioline commented
@cbrzn any changes still need to be made ? I'd like to switch to another issues, but dont want to mess with branches in case I need to make corrections

2021-09-20 14:48 UTC, cbrzn reviewed
Looks amazing on all mobile devices! There's a super small details but all good :) Thanks for this - Left a few comments

<img width="706" alt="Screenshot 2021-09-20 at 16 48 06" src="https://user-images.githubusercontent.com/21031138/134022916-e4a97091-4036-4d5f-9018-2cfbbae0bd39.png">
es

2021-09-20 14:48 UTC, cbrzn commented on src/components/Navigation/Navbar.tsx
> +      sx={{
should this be moved to a variable?

2021-09-20 14:48 UTC, cbrzn commented on src/components/Navigation/Navbar.tsx
> +          display: "flex",
same here

2021-09-20 14:48 UTC, cbrzn commented on src/components/Playground/Playground.tsx
> +                sx={{
Shouldn't we move this to styles file since we have one for this comment? Applies for all the inline style

2021-09-20 14:48 UTC, cbrzn commented on src/components/SearchBar/SearchBar.tsx
> +  }, []);
i think router should be added as a dependency here (not sure tho)

2021-09-20 14:48 UTC, cbrzn commented on src/context/ResponsiveContext.ts
> +import { createContext, Dispatch, SetStateAction } from "react";
I think that we should remove the context folder and create the contexts inside of the hooks and export them from it.

For example, for the Responsive context, I would create a `useResponsive` file inside of `hooks` folder (which already exists but I'd remove the `context` word because I feel it's not important) - And in this file export three variables which are:

- The context itself 
- A wrapper of the provider (Check this example: https://github.com/dOrgTech/arc.react-demo/blob/dev/src/utils/auth.tsx#L20-L43)
- The `useResponsive` hook itself (which would be `export const useResponsive = useContext(MyContext)`

Note that I think this should be done for `CreateApiContext` and `ResponsiveContext` - This way it's easier to interact with the context i'd say.

Please let me now if you'd like to discuss this or have any thoughts/question 🙏

2021-09-20 16:00 UTC, cbrzn approved these changes

2021-09-20 16:01 UTC, merged

2021-09-21 07:43 UTC, Brioline commented on src/components/+CreateApi/ErrorMsg.tsx
> +import styles from "./+UploadBy/styles";
left "styles.[name]" to be more explainable